stages:
  - build
  - lint_format
  - migration
  - test
  - deploy


build-job:
  stage: build
  before_script:
    - cp ${ENV} .env
    - cp ${ENV_TEST} .env-test
  script:
    - docker build -t booking-api-image .

Lint:
  stage: lint_format
  script:
    - docker run --rm --network myNetwork booking-api-image ruff check


Format:
  stage: lint_format
  script:
    - docker run --rm --network myNetwork booking-api-image ruff format --check



Migrations:
  stage: migration
  script: docker run --rm --network myNetwork booking-api-image alembic upgrade head


Tests:
  stage: test
  script: docker run --rm --network myNetwork booking-api-image pytest -s



deploy-job:
  stage: deploy
  script:
    - docker compose --file docker-compose-ci.yml up -d
    - docker exec booking_nginx nginx -s reload





