"""review23332323

Revision ID: c7cd813e85e9
Revises: 4667c3eebd20
Create Date: 2025-04-14 09:55:53.793931

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c7cd813e85e9"
down_revision: Union[str, None] = "4667c3eebd20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "hotels", ["title"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "hotels", type_="unique")
    # ### end Alembic commands ###
