"""bookings

Revision ID: c1bce5f41333
Revises: 40d3f3d93965
Create Date: 2025-03-13 16:12:31.967151

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c1bce5f41333"
down_revision: Union[str, None] = "40d3f3d93965"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "rooms_id", sa.Integer(), nullable=False, foreign_key="room.id"
        ),
        sa.Column(
            "user_id", sa.Integer(), nullable=False, foreign_key="user.id"
        ),
        sa.Column("date_from", sa.Date(), nullable=False),
        sa.Column("date_to", sa.Date(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bookings")
    # ### end Alembic commands ###
