"""bookings

Revision ID: 9f8789321654
Revises: 3e590a9fc2d0
Create Date: 2025-03-13 22:46:58.640216

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9f8789321654"
down_revision: Union[str, None] = "3e590a9fc2d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookings", sa.Column("room_id", sa.Integer(), nullable=False))
    op.drop_constraint("bookings_rooms_id_fkey", "bookings", type_="foreignkey")
    op.create_foreign_key(None, "bookings", "rooms", ["room_id"], ["id"])
    op.drop_column("bookings", "rooms_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings",
        sa.Column("rooms_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "bookings", type_="foreignkey")
    op.create_foreign_key(
        "bookings_rooms_id_fkey", "bookings", "rooms", ["rooms_id"], ["id"]
    )
    op.drop_column("bookings", "room_id")
    # ### end Alembic commands ###
