"""unique email

Revision ID: 40d3f3d93965
Revises: 10c0203c7a63
Create Date: 2025-03-05 17:38:41.430225

"""

from typing import Sequence, Union

from alembic import op



# revision identifiers, used by Alembic.
revision: str = "40d3f3d93965"
down_revision: Union[str, None] = "10c0203c7a63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    # ### end Alembic commands ###
